In [1]:
import pandas as pd
from sklearn.datasets import load_iris
import keras

Using TensorFlow backend.


In [2]:
iris=load_iris()

In [3]:
iris['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [7]:
iris.values()

dict_values([array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
 

In [8]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
X=pd.DataFrame(data=iris.data, \
               columns=['sepal_length','sepal_width',\
                        'petal_length','petal_width'])

In [10]:
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [11]:
y=pd.DataFrame(data=iris.target, columns=['species_id'])

In [12]:
y.head()

species_id
0           0
1           0
2           0
3           0
4           0

In [13]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [14]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [15]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
df=pd.Categorical.from_codes(iris.target, iris.target_names)

In [17]:
df

[setosa, setosa, setosa, setosa, setosa, ..., virginica, virginica, virginica, virginica, virginica]
Length: 150
Categories (3, object): [setosa, versicolor, virginica]

In [18]:
species=y[['species_id']]

In [19]:
species['target_name']=df

In [20]:
species.head()

species_id target_name
0           0      setosa
1           0      setosa
2           0      setosa
3           0      setosa
4           0      setosa

In [21]:
iris_df = pd.concat([X, y], axis=1)

In [22]:
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width  species_id
0           5.1          3.5           1.4          0.2           0
1           4.9          3.0           1.4          0.2           0
2           4.7          3.2           1.3          0.2           0
3           4.6          3.1           1.5          0.2           0
4           5.0          3.6           1.4          0.2           0

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y,\
                                                   test_size=0.2,\
                                                   random_state=7)

In [25]:
from keras.models import Sequential
from keras.layers import Dense
from keras.losses import categorical_crossentropy
from keras.metrics import categorical_accuracy, mean_absolute_error, mse
from keras.optimizers import Adam

In [26]:
import numpy as np
seed = 7
np.random.seed(seed)

In [27]:
model = Sequential()
model.add(Dense(1, input_shape=(4,), activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(Adam(lr=0.01), loss='categorical_crossentropy', \
              metrics=['categorical_accuracy', 'accuracy'])
from keras.utils import to_categorical
history = model.fit(X_train, to_categorical(y_train), epochs=1000)

Epoch 1/1000
120/120 [==============================] - 0s 1ms/step - loss: 1.3986 - categorical_accuracy: 0.3250 - accuracy: 0.3250
Epoch 2/1000
120/120 [==============================] - 0s 49us/step - loss: 1.2668 - categorical_accuracy: 0.2833 - accuracy: 0.2833
Epoch 3/1000
120/120 [==============================] - 0s 46us/step - loss: 1.1809 - categorical_accuracy: 0.0167 - accuracy: 0.0167
Epoch 4/1000
120/120 [==============================] - 0s 49us/step - loss: 1.1075 - categorical_accuracy: 0.1000 - accuracy: 0.1000   
Epoch 5/1000
120/120 [==============================] - 0s 46us/step - loss: 1.0739 - categorical_accuracy: 0.4500 - accuracy: 0.4500
Epoch 6/1000
120/120 [==============================] - 0s 46us/step - loss: 1.0639 - categorical_accuracy: 0.6667 - accuracy: 0.6667
Epoch 7/1000
120/120 [==============================] - 0s 49us/step - loss: 1.0578 - categorical_accuracy: 0.6750 - accuracy: 0.6750
Epoch 8/1000
120/120 [==============================] - 0s 5

120/120 [==============================] - 0s 52us/step - loss: 0.4977 - categorical_accuracy: 0.6500 - accuracy: 0.6500
Epoch 62/1000
120/120 [==============================] - 0s 62us/step - loss: 0.4963 - categorical_accuracy: 0.6500 - accuracy: 0.6500
Epoch 63/1000
120/120 [==============================] - 0s 48us/step - loss: 0.4948 - categorical_accuracy: 0.6500 - accuracy: 0.6500
Epoch 64/1000
120/120 [==============================] - 0s 55us/step - loss: 0.4934 - categorical_accuracy: 0.6500 - accuracy: 0.6500
Epoch 65/1000
120/120 [==============================] - 0s 48us/step - loss: 0.4921 - categorical_accuracy: 0.6333 - accuracy: 0.6333
Epoch 66/1000
120/120 [==============================] - 0s 58us/step - loss: 0.4908 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 67/1000
120/120 [==============================] - 0s 40us/step - loss: 0.4897 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 68/1000
120/120 [==============================] - 0s 51us/step

120/120 [==============================] - 0s 47us/step - loss: 0.4615 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 122/1000
120/120 [==============================] - 0s 53us/step - loss: 0.4610 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 123/1000
120/120 [==============================] - 0s 47us/step - loss: 0.4608 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 124/1000
120/120 [==============================] - 0s 49us/step - loss: 0.4605 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 125/1000
120/120 [==============================] - 0s 52us/step - loss: 0.4613 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 126/1000
120/120 [==============================] - 0s 50us/step - loss: 0.4601 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 127/1000
120/120 [==============================] - 0s 44us/step - loss: 0.4601 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 128/1000
120/120 [==============================] - 0s 45

120/120 [==============================] - 0s 45us/step - loss: 0.4531 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 182/1000
120/120 [==============================] - 0s 48us/step - loss: 0.4532 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 183/1000
120/120 [==============================] - 0s 43us/step - loss: 0.4531 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 184/1000
120/120 [==============================] - 0s 47us/step - loss: 0.4531 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 185/1000
120/120 [==============================] - 0s 44us/step - loss: 0.4529 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 186/1000
120/120 [==============================] - 0s 47us/step - loss: 0.4528 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 187/1000
120/120 [==============================] - 0s 46us/step - loss: 0.4527 - categorical_accuracy: 0.6833 - accuracy: 0.6833
Epoch 188/1000
120/120 [==============================] - 0s 45

120/120 [==============================] - 0s 80us/step - loss: 0.2505 - categorical_accuracy: 0.9500 - accuracy: 0.9500
Epoch 242/1000
120/120 [==============================] - 0s 66us/step - loss: 0.2415 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 243/1000
120/120 [==============================] - 0s 47us/step - loss: 0.2352 - categorical_accuracy: 0.9583 - accuracy: 0.9583
Epoch 244/1000
120/120 [==============================] - 0s 56us/step - loss: 0.2308 - categorical_accuracy: 0.9667 - accuracy: 0.9667
Epoch 245/1000
120/120 [==============================] - 0s 61us/step - loss: 0.2249 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 246/1000
120/120 [==============================] - 0s 49us/step - loss: 0.2188 - categorical_accuracy: 0.9667 - accuracy: 0.9667
Epoch 247/1000
120/120 [==============================] - 0s 46us/step - loss: 0.2168 - categorical_accuracy: 0.9583 - accuracy: 0.9583
Epoch 248/1000
120/120 [==============================] - 0s 48

120/120 [==============================] - 0s 45us/step - loss: 0.1224 - categorical_accuracy: 0.9667 - accuracy: 0.9667
Epoch 302/1000
120/120 [==============================] - 0s 48us/step - loss: 0.1199 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 303/1000
120/120 [==============================] - 0s 50us/step - loss: 0.1190 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 304/1000
120/120 [==============================] - 0s 56us/step - loss: 0.1190 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 305/1000
120/120 [==============================] - 0s 52us/step - loss: 0.1167 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 306/1000
120/120 [==============================] - 0s 64us/step - loss: 0.1163 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 307/1000
120/120 [==============================] - 0s 50us/step - loss: 0.1187 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 308/1000
120/120 [==============================] - 0s 52

120/120 [==============================] - 0s 60us/step - loss: 0.0914 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 362/1000
120/120 [==============================] - 0s 49us/step - loss: 0.0930 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 363/1000
120/120 [==============================] - 0s 62us/step - loss: 0.0892 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 364/1000
120/120 [==============================] - 0s 50us/step - loss: 0.0888 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 365/1000
120/120 [==============================] - 0s 56us/step - loss: 0.0935 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 366/1000
120/120 [==============================] - 0s 64us/step - loss: 0.0901 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 367/1000
120/120 [==============================] - 0s 54us/step - loss: 0.0891 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 368/1000
120/120 [==============================] - 0s 63

120/120 [==============================] - 0s 55us/step - loss: 0.0780 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 422/1000
120/120 [==============================] - 0s 52us/step - loss: 0.0760 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 423/1000
120/120 [==============================] - 0s 51us/step - loss: 0.0762 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 424/1000
120/120 [==============================] - 0s 44us/step - loss: 0.0758 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 425/1000
120/120 [==============================] - 0s 61us/step - loss: 0.0751 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 426/1000
120/120 [==============================] - 0s 99us/step - loss: 0.0787 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 427/1000
120/120 [==============================] - 0s 65us/step - loss: 0.0752 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 428/1000
120/120 [==============================] - 0s 52

120/120 [==============================] - 0s 49us/step - loss: 0.0681 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 482/1000
120/120 [==============================] - 0s 72us/step - loss: 0.0684 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 483/1000
120/120 [==============================] - 0s 45us/step - loss: 0.0673 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 484/1000
120/120 [==============================] - 0s 48us/step - loss: 0.0676 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 485/1000
120/120 [==============================] - 0s 45us/step - loss: 0.0668 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 486/1000
120/120 [==============================] - 0s 71us/step - loss: 0.0691 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 487/1000
120/120 [==============================] - 0s 49us/step - loss: 0.0686 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 488/1000
120/120 [==============================] - 0s 56

120/120 [==============================] - 0s 72us/step - loss: 0.0638 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 542/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0626 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 543/1000
120/120 [==============================] - 0s 52us/step - loss: 0.0620 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 544/1000
120/120 [==============================] - 0s 80us/step - loss: 0.0626 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 545/1000
120/120 [==============================] - 0s 45us/step - loss: 0.0624 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 546/1000
120/120 [==============================] - 0s 54us/step - loss: 0.0614 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 547/1000
120/120 [==============================] - 0s 53us/step - loss: 0.0638 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 548/1000
120/120 [==============================] - 0s 49

120/120 [==============================] - 0s 48us/step - loss: 0.0589 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 602/1000
120/120 [==============================] - 0s 48us/step - loss: 0.0591 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 603/1000
120/120 [==============================] - 0s 52us/step - loss: 0.0582 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 604/1000
120/120 [==============================] - 0s 58us/step - loss: 0.0584 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 605/1000
120/120 [==============================] - 0s 51us/step - loss: 0.0587 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 606/1000
120/120 [==============================] - 0s 56us/step - loss: 0.0584 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 607/1000
120/120 [==============================] - 0s 57us/step - loss: 0.0584 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 608/1000
120/120 [==============================] - 0s 47

120/120 [==============================] - 0s 58us/step - loss: 0.0577 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 662/1000
120/120 [==============================] - 0s 56us/step - loss: 0.0584 - categorical_accuracy: 0.9750 - accuracy: 0.9750
Epoch 663/1000
120/120 [==============================] - 0s 54us/step - loss: 0.0567 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 664/1000
120/120 [==============================] - 0s 47us/step - loss: 0.0571 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 665/1000
120/120 [==============================] - 0s 52us/step - loss: 0.0569 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 666/1000
120/120 [==============================] - 0s 51us/step - loss: 0.0573 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 667/1000
120/120 [==============================] - 0s 44us/step - loss: 0.0558 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 668/1000
120/120 [==============================] - 0s 48

120/120 [==============================] - 0s 44us/step - loss: 0.0549 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 722/1000
120/120 [==============================] - 0s 44us/step - loss: 0.0542 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 723/1000
120/120 [==============================] - 0s 44us/step - loss: 0.0559 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 724/1000
120/120 [==============================] - 0s 42us/step - loss: 0.0543 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 725/1000
120/120 [==============================] - 0s 50us/step - loss: 0.0534 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 726/1000
120/120 [==============================] - 0s 49us/step - loss: 0.0541 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 727/1000
120/120 [==============================] - 0s 45us/step - loss: 0.0538 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 728/1000
120/120 [==============================] - 0s 40

120/120 [==============================] - 0s 50us/step - loss: 0.0520 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 782/1000
120/120 [==============================] - 0s 43us/step - loss: 0.0520 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 783/1000
120/120 [==============================] - 0s 45us/step - loss: 0.0527 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 784/1000
120/120 [==============================] - 0s 39us/step - loss: 0.0533 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 785/1000
120/120 [==============================] - 0s 51us/step - loss: 0.0527 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 786/1000
120/120 [==============================] - 0s 49us/step - loss: 0.0531 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 787/1000
120/120 [==============================] - 0s 46us/step - loss: 0.0526 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 788/1000
120/120 [==============================] - 0s 42

120/120 [==============================] - 0s 45us/step - loss: 0.0509 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 842/1000
120/120 [==============================] - 0s 40us/step - loss: 0.0508 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 843/1000
120/120 [==============================] - 0s 44us/step - loss: 0.0514 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 844/1000
120/120 [==============================] - 0s 48us/step - loss: 0.0509 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 845/1000
120/120 [==============================] - 0s 46us/step - loss: 0.0507 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 846/1000
120/120 [==============================] - 0s 51us/step - loss: 0.0512 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 847/1000
120/120 [==============================] - 0s 44us/step - loss: 0.0508 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 848/1000
120/120 [==============================] - 0s 46

120/120 [==============================] - 0s 42us/step - loss: 0.0509 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 902/1000
120/120 [==============================] - 0s 46us/step - loss: 0.0488 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 903/1000
120/120 [==============================] - 0s 41us/step - loss: 0.0500 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 904/1000
120/120 [==============================] - 0s 47us/step - loss: 0.0512 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 905/1000
120/120 [==============================] - 0s 44us/step - loss: 0.0497 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 906/1000
120/120 [==============================] - 0s 42us/step - loss: 0.0505 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 907/1000
120/120 [==============================] - 0s 44us/step - loss: 0.0500 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 908/1000
120/120 [==============================] - 0s 45

120/120 [==============================] - 0s 44us/step - loss: 0.0502 - categorical_accuracy: 0.9833 - accuracy: 0.9833
Epoch 962/1000
120/120 [==============================] - 0s 49us/step - loss: 0.0512 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 963/1000
120/120 [==============================] - 0s 41us/step - loss: 0.0496 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 964/1000
120/120 [==============================] - 0s 44us/step - loss: 0.0485 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 965/1000
120/120 [==============================] - 0s 47us/step - loss: 0.0494 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 966/1000
120/120 [==============================] - 0s 41us/step - loss: 0.0487 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 967/1000
120/120 [==============================] - 0s 42us/step - loss: 0.0488 - categorical_accuracy: 0.9917 - accuracy: 0.9917
Epoch 968/1000
120/120 [==============================] - 0s 41

In [28]:
X_train.shape

(120, 4)

In [29]:
X_train.head()

sepal_length  sepal_width  petal_length  petal_width
126           6.2          2.8           4.8          1.8
79            5.7          2.6           3.5          1.0
22            4.6          3.6           1.0          0.2
139           6.9          3.1           5.4          2.1
74            6.4          2.9           4.3          1.3

In [30]:
y_train.shape

(120, 1)

In [31]:
y_train.head()

species_id
126           2
79            1
22            0
139           2
74            1

In [32]:
X_test.shape

(30, 4)

In [33]:
X_test.head()

sepal_length  sepal_width  petal_length  petal_width
149           5.9          3.0           5.1          1.8
84            5.4          3.0           4.5          1.5
40            5.0          3.5           1.3          0.3
66            5.6          3.0           4.5          1.5
106           4.9          2.5           4.5          1.7

In [34]:
y_test.shape

(30, 1)

In [35]:
y_test.head()

species_id
149           2
84            1
40            0
66            1
106           2

In [36]:
y_pred=model.predict(X_test)

In [37]:
y_pred

array([[6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [7.3396191e-06, 1.7344713e-01, 8.2654554e-01],
       [9.9949133e-01, 5.0861272e-04, 2.1749935e-30],
       [5.0008290e-05, 6.4271349e-01, 3.5723642e-01],
       [6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [9.9153721e-01, 8.4628146e-03, 7.5629771e-25],
       [1.0395190e-03, 9.9890137e-01, 5.9044931e-05],
       [5.0486054e-04, 9.9874121e-01, 7.5403677e-04],
       [9.9817801e-01, 1.8220155e-03, 7.0567999e-28],
       [1.1027694e-03, 9.9884927e-01, 4.7927548e-05],
       [1.0476369e-04, 8.8687891e-01, 1.1301636e-01],
       [2.3233780e-04, 9.8863900e-01, 1.1128644e-02],
       [9.9989843e-01, 1.0160494e-04, 1.4783664e-33],
       [6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [9.9974161e-01, 2.5833279e-04, 1.0115064e-31],
       [6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [9.9952507e-01, 4.748

In [38]:
X_test

sepal_length  sepal_width  petal_length  petal_width
149           5.9          3.0           5.1          1.8
84            5.4          3.0           4.5          1.5
40            5.0          3.5           1.3          0.3
66            5.6          3.0           4.5          1.5
106           4.9          2.5           4.5          1.7
41            4.5          2.3           1.3          0.3
52            6.9          3.1           4.9          1.5
94            5.6          2.7           4.2          1.3
11            4.8          3.4           1.6          0.2
51            6.4          3.2           4.5          1.5
77            6.7          3.0           5.0          1.7
85            6.0          3.4           4.5          1.6
32            5.2          4.1           1.5          0.1
109           7.2          3.6           6.1          2.5
28            5.2          3.4           1.4          0.2
70            5.9          3.2           4.8          1.8
108           6.7          2.5           5.8          1.8
137           6.4          3.1           5.5          1.8
46            5.1          3.8           1.6          0.2
37            4.9          3.6           1.4          0.1
82            5.8          2.7           3.9          1.2
120           6.9          3.2           5.7          2.3
63            6.1          2.9           4.7          1.4
119           6.0          2.2           5.0          1.5
129           7.2          3.0           5.8          1.6
138           6.0          3.0           4.8          1.8
97            6.2          2.9           4.3          1.3
80            5.5          2.4           3.8          1.1
101           5.8          2.7           5.1          1.9
140           6.7          3.1           5.6          2.4

In [39]:
y_pred_class = np.argmax(y_pred,axis=1)

In [40]:
y_test.head()

species_id
149           2
84            1
40            0
66            1
106           2

In [41]:
y_pred_class

array([2, 2, 0, 1, 2, 0, 1, 1, 0, 1, 1, 1, 0, 2, 0, 2, 2, 2, 0, 0, 1, 2,
       1, 2, 2, 2, 1, 1, 2, 2])

In [42]:
y_test['pred']=y_pred_class

/Users/akaghzi/Projects/Python/datascience/iba/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [43]:
y_test

species_id  pred
149           2     2
84            1     2
40            0     0
66            1     1
106           2     2
41            0     0
52            1     1
94            1     1
11            0     0
51            1     1
77            1     1
85            1     1
32            0     0
109           2     2
28            0     0
70            1     2
108           2     2
137           2     2
46            0     0
37            0     0
82            1     1
120           2     2
63            1     1
119           2     2
129           2     2
138           2     2
97            1     1
80            1     1
101           2     2
140           2     2

In [44]:
import matplotlib.pyplot as plt
plt.figure(figsize=[16,5])
plt.plot(history.history['loss'])
plt.show()

<Figure size 1600x500 with 1 Axes>

In [45]:
from sklearn.metrics import accuracy_score
print(f'Accuracy: {accuracy_score(y_test.species_id.values, y_test.pred.values)}')

Accuracy: 0.9333333333333333


In [46]:
from sklearn.metrics import confusion_matrix

In [47]:
confusion_matrix(y_test.species_id.values, y_test.pred.values)

array([[ 7,  0,  0],
       [ 0, 10,  2],
       [ 0,  0, 11]])

In [48]:
model.save('nn.hd5')

In [49]:
from keras.models import load_model

In [50]:
mysavedmodel = load_model('nn.hd5')

In [51]:
mysavedmodel.predict(X_test)

array([[6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [7.3396191e-06, 1.7344713e-01, 8.2654554e-01],
       [9.9949133e-01, 5.0861272e-04, 2.1749935e-30],
       [5.0008290e-05, 6.4271349e-01, 3.5723642e-01],
       [6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [9.9153721e-01, 8.4628146e-03, 7.5629771e-25],
       [1.0395190e-03, 9.9890137e-01, 5.9044931e-05],
       [5.0486054e-04, 9.9874121e-01, 7.5403677e-04],
       [9.9817801e-01, 1.8220155e-03, 7.0567999e-28],
       [1.1027694e-03, 9.9884927e-01, 4.7927548e-05],
       [1.0476369e-04, 8.8687891e-01, 1.1301636e-01],
       [2.3233780e-04, 9.8863900e-01, 1.1128644e-02],
       [9.9989843e-01, 1.0160494e-04, 1.4783664e-33],
       [6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [9.9974161e-01, 2.5833279e-04, 1.0115064e-31],
       [6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [6.9744476e-07, 2.8723313e-02, 9.7127604e-01],
       [9.9952507e-01, 4.748

In [52]:
model.save_weights('nn_weights.hd5')

In [55]:
newModel = Sequential()

In [57]:
newModel.add(Dense(1, input_shape=(4,), activation='relu'))
newModel.add(Dense(3, activation='softmax'))
newModel.compile(Adam(lr=0.01), loss='categorical_crossentropy', \
              metrics=['categorical_accuracy', 'accuracy'])

In [58]:
newModel.get_weights()

[array([[ 0.01023781],
        [-0.7340434 ],
        [ 0.9436052 ],
        [-0.5247995 ]], dtype=float32),
 array([0.], dtype=float32),
 array([[ 0.46020877,  1.163695  , -0.35056937]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [59]:
newModel.load_weights('nn_weights.hd5')

In [60]:
newModel.get_weights()

[array([[ 1.5255764 ],
        [ 0.54145944],
        [-1.8456422 ],
        [-2.730818  ]], dtype=float32),
 array([2.8173797], dtype=float32),
 array([[ 4.4517846,  2.4555635, -4.586651 ]], dtype=float32),
 array([-9.807717 ,  0.8180794,  4.338981 ], dtype=float32)]