In [4]:
data=[{'c':[20,25,13,60,30,33],
      'f':[68,77,56,140,86,92]}]

In [5]:
import pandas as pd

In [6]:
df = pd.DataFrame(data[0])

In [7]:
df

c    f
0  20   68
1  25   77
2  13   56
3  60  140
4  30   86
5  33   92

In [8]:
import matplotlib.pyplot as plt
df.plot()
plt.show()

<Figure size 640x480 with 1 Axes>

In [9]:
df.corr()

c        f
c  1.00000  0.99995
f  0.99995  1.00000

In [10]:
from sklearn.linear_model import LinearRegression

In [11]:
lr = LinearRegression()

In [12]:
lr.fit(X=df.iloc[:,:1],y=df.iloc[:,-1:].values)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
import numpy as np
newValues = np.array(15).reshape(-1,1)

In [14]:
import pickle

In [15]:
fileName='lr.pkl'

In [16]:
pickle.dump(lr, open(fileName, 'wb'))

In [18]:
lrModel = pickle.load(open('lr.pkl', 'rb'))

In [19]:
prediction = lrModel.predict(newValues)

In [20]:
prediction

array([[59.29860149]])

In [16]:
prediction = lr.predict(newValues)

In [17]:
prediction

array([[59.29860149]])

In [18]:
newValues = np.array(10).reshape(-1,1)

In [19]:
prediction = lr.predict(newValues)
print(prediction)

[[50.33110747]]


In [20]:
lr.coef_

array([[1.7934988]])

In [21]:
lr.intercept_

array([32.39611944])

In [22]:
lr.rank_

1

In [23]:
lr.score(np.array([10,15]).reshape(-1,1),np.array([50,59]).reshape(-1,1))

0.9950914813471814

In [24]:
df

c    f
0  20   68
1  25   77
2  13   56
3  60  140
4  30   86
5  33   92

In [64]:
mpg = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data", header=None)

In [65]:
mpg.head()

0    1            2    3    4     5            6    7      8     9   ...  \
0   3    ?  alfa-romero  gas  std   two  convertible  rwd  front  88.6  ...   
1   3    ?  alfa-romero  gas  std   two  convertible  rwd  front  88.6  ...   
2   1    ?  alfa-romero  gas  std   two    hatchback  rwd  front  94.5  ...   
3   2  164         audi  gas  std  four        sedan  fwd  front  99.8  ...   
4   2  164         audi  gas  std  four        sedan  4wd  front  99.4  ...   

    16    17    18    19    20   21    22  23  24     25  
0  130  mpfi  3.47  2.68   9.0  111  5000  21  27  13495  
1  130  mpfi  3.47  2.68   9.0  111  5000  21  27  16500  
2  152  mpfi  2.68  3.47   9.0  154  5000  19  26  16500  
3  109  mpfi  3.19  3.40  10.0  102  5500  24  30  13950  
4  136  mpfi  3.19  3.40   8.0  115  5500  18  22  17450  

[5 rows x 26 columns]

In [66]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
0     205 non-null int64
1     205 non-null object
2     205 non-null object
3     205 non-null object
4     205 non-null object
5     205 non-null object
6     205 non-null object
7     205 non-null object
8     205 non-null object
9     205 non-null float64
10    205 non-null float64
11    205 non-null float64
12    205 non-null float64
13    205 non-null int64
14    205 non-null object
15    205 non-null object
16    205 non-null int64
17    205 non-null object
18    205 non-null object
19    205 non-null object
20    205 non-null float64
21    205 non-null object
22    205 non-null object
23    205 non-null int64
24    205 non-null int64
25    205 non-null object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB


In [72]:
mpg.columns=['symboling',
'normalized-losses',
'make',
'fuel-type',
'aspiration',    
'num-of-doors',     
'body-style',    
'drive-wheels', 
'engine-location',  
'wheel-base',       
'length',           
'width',          
'height',     
'curb-weight',     
'engine-type',      
'num-of-cylinders', 
'engine-size',     
'fuel-system',      
'bore',          
'stroke',
'compression-ratio',
'horsepower',       
'peak-rpm',        
'city-mpg',     
'highway-mpg',
'price']

In [73]:
mpg

symboling normalized-losses         make fuel-type aspiration  \
0            3                 ?  alfa-romero       gas        std   
1            3                 ?  alfa-romero       gas        std   
2            1                 ?  alfa-romero       gas        std   
3            2               164         audi       gas        std   
4            2               164         audi       gas        std   
..         ...               ...          ...       ...        ...   
200         -1                95        volvo       gas        std   
201         -1                95        volvo       gas      turbo   
202         -1                95        volvo       gas        std   
203         -1                95        volvo    diesel      turbo   
204         -1                95        volvo       gas      turbo   

    num-of-doors   body-style drive-wheels engine-location  wheel-base  ...  \
0            two  convertible          rwd           front        88.6  ...   
1            two  convertible          rwd           front        88.6  ...   
2            two    hatchback          rwd           front        94.5  ...   
3           four        sedan          fwd           front        99.8  ...   
4           four        sedan          4wd           front        99.4  ...   
..           ...          ...          ...             ...         ...  ...   
200         four        sedan          rwd           front       109.1  ...   
201         four        sedan          rwd           front       109.1  ...   
202         four        sedan          rwd           front       109.1  ...   
203         four        sedan          rwd           front       109.1  ...   
204         four        sedan          rwd           front       109.1  ...   

     engine-size  fuel-system  bore  stroke compression-ratio horsepower  \
0            130         mpfi  3.47    2.68               9.0        111   
1            130         mpfi  3.47    2.68               9.0        111   
2            152         mpfi  2.68    3.47               9.0        154   
3            109         mpfi  3.19    3.40              10.0        102   
4            136         mpfi  3.19    3.40               8.0        115   
..           ...          ...   ...     ...               ...        ...   
200          141         mpfi  3.78    3.15               9.5        114   
201          141         mpfi  3.78    3.15               8.7        160   
202          173         mpfi  3.58    2.87               8.8        134   
203          145          idi  3.01    3.40              23.0        106   
204          141         mpfi  3.78    3.15               9.5        114   

     peak-rpm city-mpg highway-mpg  price  
0        5000       21          27  13495  
1        5000       21          27  16500  
2        5000       19          26  16500  
3        5500       24          30  13950  
4        5500       18          22  17450  
..        ...      ...         ...    ...  
200      5400       23          28  16845  
201      5300       19          25  19045  
202      5500       18          23  21485  
203      4800       26          27  22470  
204      5400       19          25  22625  

[205 rows x 26 columns]

In [75]:
mpg.replace('?',None,inplace=True)

symboling            None
normalized-losses    None
make                 None
fuel-type            None
aspiration           None
num-of-doors         None
body-style           None
drive-wheels         None
engine-location      None
wheel-base           None
length               None
width                None
height               None
curb-weight          None
engine-type          None
num-of-cylinders     None
engine-size          None
fuel-system          None
bore                 None
stroke               None
compression-ratio    None
horsepower           None
peak-rpm             None
city-mpg             None
highway-mpg          None
price                None
dtype: object

In [76]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
symboling            205 non-null int64
normalized-losses    205 non-null object
make                 205 non-null object
fuel-type            205 non-null object
aspiration           205 non-null object
num-of-doors         205 non-null object
body-style           205 non-null object
drive-wheels         205 non-null object
engine-location      205 non-null object
wheel-base           205 non-null float64
length               205 non-null float64
width                205 non-null float64
height               205 non-null float64
curb-weight          205 non-null int64
engine-type          205 non-null object
num-of-cylinders     205 non-null object
engine-size          205 non-null int64
fuel-system          205 non-null object
bore                 205 non-null object
stroke               205 non-null object
compression-ratio    205 non-null float64
horsepower           205 non-nul

In [78]:
mpg['price'].fillna(mpg['price'].mean(),inplace=True)

TypeError: Could not convert 134951650016500139501745015250177101892023875?1643016925209702110524565307604131536880515162956575557263777957622966927609855889211296464796855539965297129729572957895909588451029512945103456785??11048322503555036000519560956795669573951094511845136451564588458495105951024510795112451828018344255522824828176316003418435056409604540016503538961896669768999598499126291486914489698981899279927954997099664968497349729977997499799982498949954913499143991349917199196991839911900132001244013860155801690016695170751663017950181505572795762296692760989211276422018325283402837028?9295989511850121701504015510181501862051187053760371267775996092331125974631019880131169453486338648869187898877869387198789877887738835892588058823892989538844996399989111991154917669894810698998810898112481655815998156901575077757975799581958495949599951159599801329513845122901294013415159851651518420189501684519045214852247022625 to numeric

In [83]:
mpg['price'].fillna(method='ffill',inplace=True)

In [84]:
mpg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
symboling            205 non-null int64
normalized-losses    205 non-null object
make                 205 non-null object
fuel-type            205 non-null object
aspiration           205 non-null object
num-of-doors         205 non-null object
body-style           205 non-null object
drive-wheels         205 non-null object
engine-location      205 non-null object
wheel-base           205 non-null float64
length               205 non-null float64
width                205 non-null float64
height               205 non-null float64
curb-weight          205 non-null int64
engine-type          205 non-null object
num-of-cylinders     205 non-null object
engine-size          205 non-null int64
fuel-system          205 non-null object
bore                 205 non-null object
stroke               205 non-null object
compression-ratio    205 non-null float64
horsepower           205 non-nul